# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080

RUN sed -i "s/Listen 80/Listen 8080/g" && \
    sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080" && \
    chgrp -R 0 /var/log/httpd && \
    chmod -R g=u /var/log/httpd

USER 1001
